    #include "yaoosl.tab.h"
    #include <stdarg.h>
    #include <stdio.h>
    #define YY_DECL int yylex(struct yaoosl_compilationunit* yyscanner)
    #define YY_INPUT(buf,result,max_size)  {\
        result = yaoosl_yylex_get_next_char(yyget_extra(yyscanner), buf, max_size); \
        if (result <= 0) { result = YY_NULL; }\
    }

#line 10 "lex.yaoosl_.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define yaoosl__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer yaoosl__create_buffer
#endif

#ifdef yy_delete_buffer
#define yaoosl__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer yaoosl__delete_buffer
#endif

#ifdef yy_scan_buffer
#define yaoosl__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer yaoosl__scan_buffer
#endif

#ifdef yy_scan_string
#define yaoosl__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string yaoosl__scan_string
#endif

#ifdef yy_scan_bytes
#define yaoosl__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes yaoosl__scan_bytes
#endif

#ifdef yy_init_buffer
#define yaoosl__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer yaoosl__init_buffer
#endif

#ifdef yy_flush_buffer
#define yaoosl__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer yaoosl__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define yaoosl__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state yaoosl__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define yaoosl__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer yaoosl__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define yaoosl_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state yaoosl_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define yaoosl_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state yaoosl_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define yaoosl_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack yaoosl_ensure_buffer_stack
#endif

#ifdef yylex
#define yaoosl_lex_ALREADY_DEFINED
#else
#define yylex yaoosl_lex
#endif

#ifdef yyrestart
#define yaoosl_restart_ALREADY_DEFINED
#else
#define yyrestart yaoosl_restart
#endif

#ifdef yylex_init
#define yaoosl_lex_init_ALREADY_DEFINED
#else
#define yylex_init yaoosl_lex_init
#endif

#ifdef yylex_init_extra
#define yaoosl_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra yaoosl_lex_init_extra
#endif

#ifdef yylex_destroy
#define yaoosl_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy yaoosl_lex_destroy
#endif

#ifdef yyget_debug
#define yaoosl_get_debug_ALREADY_DEFINED
#else
#define yyget_debug yaoosl_get_debug
#endif

#ifdef yyset_debug
#define yaoosl_set_debug_ALREADY_DEFINED
#else
#define yyset_debug yaoosl_set_debug
#endif

#ifdef yyget_extra
#define yaoosl_get_extra_ALREADY_DEFINED
#else
#define yyget_extra yaoosl_get_extra
#endif

#ifdef yyset_extra
#define yaoosl_set_extra_ALREADY_DEFINED
#else
#define yyset_extra yaoosl_set_extra
#endif

#ifdef yyget_in
#define yaoosl_get_in_ALREADY_DEFINED
#else
#define yyget_in yaoosl_get_in
#endif

#ifdef yyset_in
#define yaoosl_set_in_ALREADY_DEFINED
#else
#define yyset_in yaoosl_set_in
#endif

#ifdef yyget_out
#define yaoosl_get_out_ALREADY_DEFINED
#else
#define yyget_out yaoosl_get_out
#endif

#ifdef yyset_out
#define yaoosl_set_out_ALREADY_DEFINED
#else
#define yyset_out yaoosl_set_out
#endif

#ifdef yyget_leng
#define yaoosl_get_leng_ALREADY_DEFINED
#else
#define yyget_leng yaoosl_get_leng
#endif

#ifdef yyget_text
#define yaoosl_get_text_ALREADY_DEFINED
#else
#define yyget_text yaoosl_get_text
#endif

#ifdef yyget_lineno
#define yaoosl_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno yaoosl_get_lineno
#endif

#ifdef yyset_lineno
#define yaoosl_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno yaoosl_set_lineno
#endif

#ifdef yyget_column
#define yaoosl_get_column_ALREADY_DEFINED
#else
#define yyget_column yaoosl_get_column
#endif

#ifdef yyset_column
#define yaoosl_set_column_ALREADY_DEFINED
#else
#define yyset_column yaoosl_set_column
#endif

#ifdef yywrap
#define yaoosl_wrap_ALREADY_DEFINED
#else
#define yywrap yaoosl_wrap
#endif

#ifdef yyalloc
#define yaoosl_alloc_ALREADY_DEFINED
#else
#define yyalloc yaoosl_alloc
#endif

#ifdef yyrealloc
#define yaoosl_realloc_ALREADY_DEFINED
#else
#define yyrealloc yaoosl_realloc
#endif

#ifdef yyfree
#define yaoosl_free_ALREADY_DEFINED
#else
#define yyfree yaoosl_free
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
        *yy_cp = yyg->yy_hold_char; \
        YY_RESTORE_YY_MORE_OFFSET \
        yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */ \
        } \
    while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
    {
    FILE *yy_input_file;

    char *yy_ch_buf;		/* input buffer */
    char *yy_buf_pos;		/* current position in input buffer */

    /* Size of input buffer in bytes, not including room for EOB
     * characters.
     */
    int yy_buf_size;

    /* Number of characters read into yy_ch_buf, not including EOB
     * characters.
     */
    int yy_n_chars;

    /* Whether we "own" the buffer - i.e., we know we created it,
     * and can realloc() it to grow it, and should free() it to
     * delete it.
     */
    int yy_is_our_buffer;

    /* Whether this is an "interactive" input source; if so, and
     * if we're using stdio for input, then we want to use getc()
     * instead of fread(), to make sure we stop fetching input after
     * each newline.
     */
    int yy_is_interactive;

    /* Whether we're considered to be at the beginning of a line.
     * If so, '^' rules will be active on the next match, otherwise
     * not.
     */
    int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

    /* Whether to try to fill the input buffer when we reach the
     * end of it.
     */
    int yy_fill_buffer;

    int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2

    };
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
    { \
    if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
        YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
    } \
    YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
    }
#define yy_set_bol(at_bol) \
    { \
    if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
        YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
    } \
    YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
    }
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yaoosl_wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
    yyg->yytext_ptr = yy_bp; \
    yyleng = (int) (yy_cp - yy_bp); \
    yyg->yy_hold_char = *yy_cp; \
    *yy_cp = '\0'; \
    yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 105
#define YY_END_OF_BUFFER 106
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
    {
    flex_int32_t yy_verify;
    flex_int32_t yy_nxt;
    };
static const flex_int16_t yy_accept[518] =
    {   0,
        0,    0,    0,    0,  106,  105,  103,   73,  105,   89,
       83,  105,   49,   50,   62,   59,   54,   61,   97,   63,
       98,   98,    7,   53,   66,   76,   69,   90,  104,   51,
       52,   80,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,   47,
       93,   48,   78,    6,    6,    5,    6,    6,    6,    6,
        6,    6,    6,    4,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,

        6,    6,   71,    0,    0,  101,    0,   88,   82,   81,
        0,  102,    0,   85,   58,    0,   98,   87,   60,   86,
       98,    2,    1,   84,    0,    0,    0,   64,   65,   70,
       68,   67,  104,   79,  104,  104,  104,  104,  104,  104,
      104,  104,  104,   22,  104,  104,  104,  104,  104,  104,
       18,  104,   94,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
       91,   92,   77,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    3,    6,    6,    6,    6,
        6,    6,    6,    1,    6,    6,    6,    6,    6,    6,

        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,   72,  101,  102,    1,  100,    0,
       98,   99,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,   20,   55,  104,  104,
       12,  104,  104,  104,  104,  104,   56,  104,  104,  104,
      104,  104,   23,  104,  104,  104,  104,  104,  104,    6,
        6,    6,    1,    6,    6,    6,    6,    6,    6,    6,

        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,   75,   33,   34,  104,  104,   36,
      104,  104,  104,  104,   19,  104,  104,  104,  104,  104,
      104,   37,  104,  104,   27,  104,  104,  104,  104,  104,
      104,   57,  104,   95,  104,  104,  104,   26,  104,    9,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,

        6,    6,    6,    6,    6,    6,   28,   24,   10,  104,
      104,  104,  104,   96,   45,   39,   41,   43,  104,  104,
      104,  104,  104,  104,  104,  104,   25,  104,  104,  104,
      104,   38,    8,   21,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,  104,  104,   46,   32,  104,  104,  104,  104,
       16,   30,   17,   35,   74,   40,   42,   44,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,  104,   15,  104,  104,  104,   13,

        6,    6,    6,    6,    6,    6,   29,   14,  104,   11,
        6,    6,    6,    6,   31,    6,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   22,   24,   22,   25,   26,   27,
       28,   29,   30,    1,   31,   32,   31,   31,   33,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   34,   31,   31,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   31,   49,   50,   51,   52,
       53,   54,   31,   55,   56,   57,   58,   59,   60,   61,
       62,   31,   63,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[67] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    1,    5,    6,    1,    7,    7,    7,    7,
        7,    7,    7,    7,    1,    1,    1,    6,    1,    1,
        8,    8,    9,    8,    1,    1,    1,    1,   10,    8,
        8,    8,    8,    9,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[530] =
    {   0,
        0,    0,   66,    0,  918,  919,  919,  105,  129,  889,
      128,  128,  919,  919,  888,  126,  919,  130,  149,  132,
      159,  153,  919,  919,  112,  887,  118,  919,    0,  919,
      919,  886,  855,   97,  148,  131,  101,  146,  868,  152,
      165,  857,  152,  866,  145,  164,  101,  856,  165,  919,
      178,  919,  880,    0,    0,  919,  187,  213,  879,  210,
      219,    0,    0,  205,  244,    0,  259,  271,  218,  281,
      209,    0,    0,  204,  878,  208,    0,  342,    0,    0,
      877,  846,  199,  270,  200,  190,  207,  859,  274,  287,
      848,  170,  857,  201,  274,  107,  847,  237,    0,  243,

        0,  871,  919,  842,  154,  892,  860,  919,  919,  919,
      261,  887,  858,  919,  919,  392,    0,  919,  919,  919,
      242,  919,    0,  919,  294,  294,    0,  919,  919,  919,
      919,  919,    0,  919,  836,  836,  838,  846,  832,  848,
      847,  834,  830,  826,  827,  825,  831,  827,  824,  821,
        0,  820,    0,  825,  815,  824,  829,  824,  830,  813,
      812,  269,  280,  276,  814,  815,  818,  817,  816,  806,
      919,  919,  919,    0,    0,  806,  414,  856,  415,    0,
        0,    0,  419,  852,  417,  919,    0,  414,  407,    0,
        0,    0,  452,  848,    0,  406,  485,  509,    0,    0,

        0,    0,    0,    0,    0,  801,  801,  803,  811,  797,
      813,  812,  799,  795,  791,  792,  790,  796,  792,  789,
      786,    0,  785,    0,  790,  780,  789,  794,  789,  795,
      778,  777,  389,  284,  279,  779,  780,  783,  782,  781,
      771,    0,    0,    0,  919,  919,  919,    0,  425,  439,
      460,    0,  774,  782,  775,  784,  781,  767,  765,  763,
      771,  777,  773,  772,  759,  774,    0,    0,  468,  769,
        0,  762,  756,  751,  759,  750,    0,  750,  758,  749,
      751,  759,    0,  758,  744,  748,  756,  748,  750,    0,
        0,    0,  785,  448,  559,  567,    0,  742,  750,  743,

      752,  749,  735,  733,  731,  739,  745,  741,  740,  727,
      742,    0,    0,  574,  737,    0,  730,  724,  719,  727,
      718,    0,  718,  726,  717,  719,  727,    0,  726,  712,
      716,  724,  716,  718,    0,    0,    0,  715,  716,    0,
      706,  713,  701,  709,    0,  703,  713,  699,  732,  735,
      732,    0,  697,  695,    0,  710,  709,  700,  692,  698,
      693,    0,  684,    0,  690,  581,  696,    0,  697,    0,
        0,    0,    0,  691,  692,    0,  682,  689,  677,  685,
        0,  679,  689,  675,  708,  711,  708,    0,  673,  671,
        0,  686,  685,  676,  668,  674,  669,    0,  660,    0,

      666,  588,  672,    0,  673,    0,    0,    0,    0,  664,
      671,  670,  661,    0,    0,    0,    0,    0,  660,  657,
      653,  652,  666,  655,  656,  646,    0,  636,  655,  630,
      627,    0,    0,    0,    0,    0,    0,  588,  573,  572,
      563,    0,    0,    0,    0,    0,  562,  559,  553,  552,
      565,  551,  560,  554,    0,  551,  572,  574,  499,    0,
        0,    0,  443,  457,    0,    0,  458,  455,  441,  449,
        0,    0,    0,    0,    0,    0,    0,    0,  432,  446,
        0,    0,  427,  414,  399,  405,    0,    0,    0,    0,
        0,    0,    0,    0,  403,    0,  396,  398,  366,    0,

      309,    0,  290,  276,  261,    0,    0,    0,  204,    0,
        0,    0,  117,    0,    0,    0,  919,  618,  628,  635,
      636,  646,  656,  666,  670,  679,  686,  687,  696
    } ;

static const flex_int16_t yy_def[530] =
    {   0,
      517,    1,  517,    3,  517,  517,  517,  517,  518,  517,
      517,  519,  517,  517,  517,  520,  517,  520,  517,  517,
      517,   21,  517,  517,  517,  517,  517,  517,  521,  517,
      517,  517,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  517,
      517,  517,  517,  522,  522,  517,  522,  523,  522,  522,
      524,  522,  522,  517,  522,  522,  522,  522,  522,  522,
       70,  522,  522,  522,  522,  522,  522,  517,  522,  522,
      522,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,  522,  522,

      522,  522,  517,  517,  518,  517,  518,  517,  517,  517,
      519,  517,  519,  517,  517,  517,   22,  517,  517,  517,
      525,  517,  526,  517,  517,  527,  528,  517,  517,  517,
      517,  517,  521,  517,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      517,  517,  517,  522,  522,  522,  523,  522,  523,  522,
      522,  522,  524,  522,  524,  517,  522,  522,   70,  522,
      522,  522,  522,  529,  522,  522,  522,  517,  522,  522,

      522,  522,  522,   78,  522,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,  522,  522,  522,  517,  517,  517,  526,  517,  517,
      517,  528,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  522,
      522,  522,  529,  522,  522,  522,  198,   78,   78,   78,

       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,

       78,   78,   78,   78,   78,   78,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,  521,  521,  521,  521,  521,  521,  521,  521,
      521,  521,  521,  521,  521,  521,  521,  521,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,  521,  521,  521,  521,  521,  521,

       78,   78,   78,   78,   78,   78,  521,  521,  521,  521,
       78,   78,   78,   78,  521,   78,    0,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517
    } ;

static const flex_int16_t yy_nxt[986] =
    {   0,
        6,    7,    7,    8,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   22,   22,
       22,   22,   22,   22,   23,   24,   25,   26,   27,   28,
       29,   29,   29,   29,   30,    6,   31,   32,   29,   33,
       34,   35,   36,   37,   38,   39,   29,   40,   29,   29,
       29,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       29,   29,   50,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,   63,   64,   65,   66,   67,
       68,   69,   70,   71,   71,   71,   71,   71,   71,   71,
       72,   73,   74,   75,   76,   77,   78,   78,   78,   78,

       79,   54,   80,   81,   78,   82,   83,   84,   85,   86,
       87,   88,   78,   89,   78,   78,   78,   90,   91,   92,
       93,   94,   95,   96,   97,   98,   78,   78,   99,  100,
      101,  102,  103,  106,  109,  112,  136,  115,  128,  129,
      116,  517,  122,  119,  116,  131,  132,  123,  166,  137,
      145,  138,  104,  118,  237,  110,  167,  120,  106,  124,
      516,  146,  238,  113,  107,  121,  121,  121,  121,  121,
      121,  121,  121,  116,  143,  117,  117,  117,  117,  117,
      117,  117,  117,  144,  517,  147,  517,  139,  161,  107,
      125,  126,  127,  517,  140,  148,  151,  141,  149,  125,

      142,  162,  126,  152,  154,  171,  158,  153,  155,  159,
      163,  169,  170,  517,  175,  105,  181,  178,  164,  127,
      186,  111,  156,  105,  229,  165,  184,  230,  122,  111,
      199,  200,  114,  194,  176,  202,  203,  182,  207,  216,
      174,  172,  174,  214,  232,  195,  218,  515,  179,  174,
      217,  208,  215,  209,  185,  187,  219,  233,  188,  220,
      189,  189,  189,  189,  189,  189,  189,  189,  112,  174,
      242,  190,  191,  188,  126,  189,  189,  189,  189,  189,
      189,  189,  189,  240,  241,  126,  192,  193,  193,  193,
      193,  193,  193,  193,  193,  188,  113,  189,  189,  189,

      189,  189,  189,  189,  189,  250,  243,  250,  278,  210,
      249,  249,  196,  197,  198,  514,  211,  513,  222,  212,
      234,  196,  213,  279,  197,  223,  225,  280,  235,  224,
      226,  325,  249,  282,  281,  236,  327,  283,  326,  512,
      328,  198,  174,  174,  227,  174,  174,  174,  174,  174,
      174,  174,  511,  174,  174,  174,  174,  174,  204,  204,
      204,  204,  204,  204,  204,  204,  174,  174,  174,  174,
      174,  174,  204,  204,  204,  204,  174,  174,  174,  174,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,

      204,  204,  204,  204,  174,  174,  174,  174,  121,  121,
      121,  121,  121,  121,  121,  121,  105,  105,  178,  111,
      510,  111,  294,  294,  105,  105,  184,  111,  323,  111,
      193,  193,  193,  193,  193,  193,  193,  193,  174,  509,
      174,  249,  249,  324,  294,  508,  507,  174,  506,  179,
      179,  505,  185,  504,  185,  251,  251,  251,  251,  251,
      251,  251,  251,  249,  294,  294,  503,  174,  193,  193,
      193,  193,  193,  193,  193,  193,  251,  251,  251,  251,
      251,  251,  251,  251,  197,  349,  294,  350,  502,  501,
      351,  352,  500,  499,  498,  197,  295,  497,  295,  496,

      495,  296,  296,  296,  296,  296,  296,  296,  296,  174,
      174,  353,  174,  174,  174,  174,  174,  174,  174,  494,
      174,  174,  174,  174,  174,  297,  297,  297,  297,  297,
      297,  297,  297,  174,  174,  174,  174,  174,  174,  297,
      297,  297,  297,  174,  174,  174,  174,  174,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  174,  174,  174,  174,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  385,  493,  386,  492,  491,  387,  388,  429,  490,

      430,  489,  488,  431,  432,  457,  487,  458,  486,  485,
      459,  460,  484,  483,  482,  481,  480,  389,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  117,  479,
      117,  117,  133,  133,  133,  133,  174,  478,  477,  174,
      174,  174,  174,  174,  174,  174,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  183,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  121,  476,  121,  248,
      475,  248,  248,  248,  248,  248,  248,  248,  248,  251,
      251,  474,  251,  252,  252,  252,  293,  473,  293,  293,

      293,  293,  293,  293,  293,  293,  472,  471,  470,  469,
      468,  467,  466,  465,  464,  463,  462,  461,  456,  455,
      454,  453,  452,  451,  450,  449,  448,  447,  446,  445,
      444,  443,  442,  441,  440,  439,  438,  437,  436,  435,
      434,  433,  428,  427,  426,  425,  424,  423,  422,  421,
      420,  419,  418,  417,  416,  415,  414,  413,  412,  411,
      410,  409,  408,  407,  406,  405,  404,  403,  402,  401,
      400,  399,  398,  397,  396,  395,  394,  393,  392,  391,
      390,  384,  383,  382,  381,  380,  379,  378,  377,  376,
      375,  374,  373,  372,  371,  248,  370,  369,  368,  367,

      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  354,  348,  347,  346,  345,  344,  343,  342,
      341,  340,  339,  338,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  322,  321,  320,  319,  318,  317,  316,
      315,  314,  313,  312,  311,  310,  309,  308,  307,  306,
      305,  304,  303,  302,  301,  300,  299,  298,  248,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  277,  276,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  258,  257,  256,
      255,  254,  253,  113,  247,  107,  246,  245,  244,  239,

      231,  228,  221,  206,  205,  201,  180,  173,  168,  160,
      157,  150,  135,  134,  130,  114,  108,  517,    5,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517
    } ;

static const flex_int16_t yy_chk[986] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    8,    9,   11,   12,   34,   16,   25,   25,
       16,   18,   20,   18,   18,   27,   27,   20,   47,   34,
       37,   34,    8,   16,   96,   11,   47,   18,  105,   20,
      513,   37,   96,   12,    9,   19,   19,   19,   19,   19,
       19,   19,   19,   21,   36,   21,   21,   21,   21,   21,
       21,   21,   21,   36,   22,   38,   22,   35,   45,  105,
       21,   21,   21,   22,   35,   38,   40,   35,   38,   21,

       35,   45,   21,   40,   41,   51,   43,   40,   41,   43,
       46,   49,   49,   22,   57,   58,   60,   58,   46,   21,
       64,   61,   41,   58,   92,   46,   61,   92,   69,   61,
       74,   74,   64,   69,   57,   76,   76,   60,   83,   86,
       71,   51,   71,   85,   94,   69,   87,  509,   58,   71,
       86,   83,   85,   83,   61,   65,   87,   94,   65,   87,
       65,   65,   65,   65,   65,   65,   65,   65,  111,   71,
      100,   65,   67,   67,  121,   67,   67,   67,   67,   67,
       67,   67,   67,   98,   98,  121,   67,   68,   68,   68,
       68,   68,   68,   68,   68,   70,  111,   70,   70,   70,

       70,   70,   70,   70,   70,  126,  100,  126,  162,   84,
      125,  125,   70,   70,   70,  505,   84,  504,   89,   84,
       95,   70,   84,  162,   70,   89,   90,  163,   95,   89,
       90,  234,  125,  164,  163,   95,  235,  164,  234,  503,
      235,   70,   78,   78,   90,   78,   78,   78,   78,   78,
       78,   78,  501,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,

       78,   78,   78,   78,   78,   78,   78,   78,  116,  116,
      116,  116,  116,  116,  116,  116,  177,  179,  177,  185,
      499,  183,  196,  196,  177,  179,  183,  185,  233,  183,
      188,  188,  188,  188,  188,  188,  188,  188,  189,  498,
      189,  249,  249,  233,  196,  497,  495,  189,  486,  177,
      179,  485,  185,  484,  183,  250,  250,  250,  250,  250,
      250,  250,  250,  249,  294,  294,  483,  189,  193,  193,
      193,  193,  193,  193,  193,  193,  251,  251,  251,  251,
      251,  251,  251,  251,  193,  269,  294,  269,  480,  479,
      269,  269,  470,  469,  468,  193,  197,  467,  197,  464,

      463,  197,  197,  197,  197,  197,  197,  197,  197,  198,
      198,  269,  198,  198,  198,  198,  198,  198,  198,  459,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  295,  295,  295,  295,  295,
      295,  295,  295,  296,  296,  296,  296,  296,  296,  296,
      296,  314,  458,  314,  457,  456,  314,  314,  366,  454,

      366,  453,  452,  366,  366,  402,  451,  402,  450,  449,
      402,  402,  448,  447,  441,  440,  439,  314,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  519,  519,
      519,  519,  519,  519,  519,  519,  519,  519,  520,  438,
      520,  520,  521,  521,  521,  521,  522,  431,  430,  522,
      522,  522,  522,  522,  522,  522,  523,  523,  523,  523,
      523,  523,  523,  523,  523,  523,  524,  524,  524,  524,
      524,  524,  524,  524,  524,  524,  525,  429,  525,  526,
      428,  526,  526,  526,  526,  526,  526,  526,  526,  527,
      527,  426,  527,  528,  528,  528,  529,  425,  529,  529,

      529,  529,  529,  529,  529,  529,  424,  423,  422,  421,
      420,  419,  413,  412,  411,  410,  405,  403,  401,  399,
      397,  396,  395,  394,  393,  392,  390,  389,  387,  386,
      385,  384,  383,  382,  380,  379,  378,  377,  375,  374,
      369,  367,  365,  363,  361,  360,  359,  358,  357,  356,
      354,  353,  351,  350,  349,  348,  347,  346,  344,  343,
      342,  341,  339,  338,  334,  333,  332,  331,  330,  329,
      327,  326,  325,  324,  323,  321,  320,  319,  318,  317,
      315,  311,  310,  309,  308,  307,  306,  305,  304,  303,
      302,  301,  300,  299,  298,  293,  289,  288,  287,  286,

      285,  284,  282,  281,  280,  279,  278,  276,  275,  274,
      273,  272,  270,  266,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  241,  240,  239,
      238,  237,  236,  232,  231,  230,  229,  228,  227,  226,
      225,  223,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  194,  184,
      178,  176,  170,  169,  168,  167,  166,  165,  161,  160,
      159,  158,  157,  156,  155,  154,  152,  150,  149,  148,
      147,  146,  145,  144,  143,  142,  141,  140,  139,  138,
      137,  136,  135,  113,  112,  107,  106,  104,  102,   97,

       93,   91,   88,   82,   81,   75,   59,   53,   48,   44,
       42,   39,   33,   32,   26,   15,   10,    5,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517,  517,  517,  517,  517,  517,
      517,  517,  517,  517,  517
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "yaoosl.l"
/* Start declarations and option settings */
#define YY_NO_UNISTD_H 1
#define YY_NO_INPUT 1
/* Include bison file at the very top */


#line 1034 "lex.yaoosl_.c"

#define INITIAL 0
#define CCOMMENT 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

            int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
    if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
        { \
        int c = '*'; \
        int n; \
        for ( n = 0; n < max_size && \
                 (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
            buf[n] = (char) c; \
        if ( c == '\n' ) \
            buf[n++] = (char) c; \
        if ( c == EOF && ferror( yyin ) ) \
            YY_FATAL_ERROR( "input in flex scanner failed" ); \
        result = n; \
        } \
    else \
        { \
        errno=0; \
        while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
            { \
            if( errno != EINTR) \
                { \
                YY_FATAL_ERROR( "input in flex scanner failed" ); \
                break; \
                } \
            errno=0; \
            clearerr(yyin); \
            } \
        }\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
    YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
    yy_state_type yy_current_state;
    char *yy_cp, *yy_bp;
    int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    if ( !yyg->yy_init )
        {
        yyg->yy_init = 1;

#ifdef YY_USER_INIT
        YY_USER_INIT;
#endif

        if ( ! yyg->yy_start )
            yyg->yy_start = 1;	/* first start state */

        if ( ! yyin )
            yyin = stdin;

        if ( ! yyout )
            yyout = stdout;

        if ( ! YY_CURRENT_BUFFER ) {
            yyensure_buffer_stack (yyscanner);
            YY_CURRENT_BUFFER_LVALUE =
                yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
        }

        yy_load_buffer_state( yyscanner );
        }

    {
#line 27 "yaoosl.l"



#line 1297 "lex.yaoosl_.c"

    while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
        {
        yy_cp = yyg->yy_c_buf_p;

        /* Support of yytext. */
        *yy_cp = yyg->yy_hold_char;

        /* yy_bp points to the position in yy_ch_buf of the start of
         * the current run.
         */
        yy_bp = yy_cp;

        yy_current_state = yyg->yy_start;
yy_match:
        do
            {
            YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
            if ( yy_accept[yy_current_state] )
                {
                yyg->yy_last_accepting_state = yy_current_state;
                yyg->yy_last_accepting_cpos = yy_cp;
                }
            while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
                {
                yy_current_state = (int) yy_def[yy_current_state];
                if ( yy_current_state >= 518 )
                    yy_c = yy_meta[yy_c];
                }
            yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
            ++yy_cp;
            }
        while ( yy_current_state != 517 );
        yy_cp = yyg->yy_last_accepting_cpos;
        yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
        yy_act = yy_accept[yy_current_state];

        YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

        switch ( yy_act )
    { /* beginning of action switch */
            case 0: /* must back up */
            /* undo the effects of YY_DO_BEFORE_ACTION */
            *yy_cp = yyg->yy_hold_char;
            yy_cp = yyg->yy_last_accepting_cpos;
            yy_current_state = yyg->yy_last_accepting_state;
            goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 30 "yaoosl.l"
;
    YY_BREAK
case 2:
YY_RULE_SETUP
#line 31 "yaoosl.l"
{ BEGIN(CCOMMENT); }
    YY_BREAK

case 3:
YY_RULE_SETUP
#line 33 "yaoosl.l"
{ BEGIN(INITIAL); }
    YY_BREAK
case 4:
YY_RULE_SETUP
#line 34 "yaoosl.l"
; // eat the lone star
    YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 35 "yaoosl.l"
{ yylineno++; }
    YY_BREAK
case 6:
YY_RULE_SETUP
#line 36 "yaoosl.l"
; // eat comment in chunks 
    YY_BREAK

case 7:
YY_RULE_SETUP
#line 38 "yaoosl.l"
{ return YST_COLON; }
    YY_BREAK
case 8:
YY_RULE_SETUP
#line 39 "yaoosl.l"
{ return YST_USING; }
    YY_BREAK
case 9:
YY_RULE_SETUP
#line 40 "yaoosl.l"
{ return YST_WITH; }
    YY_BREAK
case 10:
YY_RULE_SETUP
#line 41 "yaoosl.l"
{ return YST_CLASS; }
    YY_BREAK
case 11:
YY_RULE_SETUP
#line 42 "yaoosl.l"
{ return YST_OPERATOR; }
    YY_BREAK
case 12:
YY_RULE_SETUP
#line 43 "yaoosl.l"
{ return YST_NEW; }
    YY_BREAK
case 13:
YY_RULE_SETUP
#line 44 "yaoosl.l"
{ return YST_PRIVATE; }
    YY_BREAK
case 14:
YY_RULE_SETUP
#line 45 "yaoosl.l"
{ return YST_INTERNAL; }
    YY_BREAK
case 15:
YY_RULE_SETUP
#line 46 "yaoosl.l"
{ return YST_DERIVED; }
    YY_BREAK
case 16:
YY_RULE_SETUP
#line 47 "yaoosl.l"
{ return YST_PUBLIC; }
    YY_BREAK
case 17:
YY_RULE_SETUP
#line 48 "yaoosl.l"
{ return YST_STATIC; }
    YY_BREAK
case 18:
YY_RULE_SETUP
#line 49 "yaoosl.l"
{ return YST_IF; }
    YY_BREAK
case 19:
YY_RULE_SETUP
#line 50 "yaoosl.l"
{ return YST_ELSE; }
    YY_BREAK
case 20:
YY_RULE_SETUP
#line 51 "yaoosl.l"
{ return YST_FOR; }
    YY_BREAK
case 21:
YY_RULE_SETUP
#line 52 "yaoosl.l"
{ return YST_WHILE; }
    YY_BREAK
case 22:
YY_RULE_SETUP
#line 53 "yaoosl.l"
{ return YST_DO; }
    YY_BREAK
case 23:
YY_RULE_SETUP
#line 54 "yaoosl.l"
{ return YST_TRY; }
    YY_BREAK
case 24:
YY_RULE_SETUP
#line 55 "yaoosl.l"
{ return YST_CATCH; }
    YY_BREAK
case 25:
YY_RULE_SETUP
#line 56 "yaoosl.l"
{ return YST_THROW; }
    YY_BREAK
case 26:
YY_RULE_SETUP
#line 57 "yaoosl.l"
{ return YST_VOID; }
    YY_BREAK
case 27:
YY_RULE_SETUP
#line 58 "yaoosl.l"
{ return YST_NULL; }
    YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "yaoosl.l"
{ return YST_BREAK; }
    YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "yaoosl.l"
{ return YST_CONTINUE; }
    YY_BREAK
case 30:
YY_RULE_SETUP
#line 61 "yaoosl.l"
{ return YST_RETURN; }
    YY_BREAK
case 31:
YY_RULE_SETUP
#line 62 "yaoosl.l"
{ return YST_NAMESPACE; }
    YY_BREAK
case 32:
YY_RULE_SETUP
#line 63 "yaoosl.l"
{ return YST_EXTERN; }
    YY_BREAK
case 33:
YY_RULE_SETUP
#line 64 "yaoosl.l"
{ return YST_BASE; }
    YY_BREAK
case 34:
YY_RULE_SETUP
#line 66 "yaoosl.l"
{ return YST_BOOL; }
    YY_BREAK
case 35:
YY_RULE_SETUP
#line 67 "yaoosl.l"
{ return YST_STRING; }
    YY_BREAK
case 36:
YY_RULE_SETUP
#line 68 "yaoosl.l"
{ return YST_CHAR; }
    YY_BREAK
case 37:
YY_RULE_SETUP
#line 69 "yaoosl.l"
{ return YST_INT8; }
    YY_BREAK
case 38:
YY_RULE_SETUP
#line 70 "yaoosl.l"
{ return YST_UINT8; }
    YY_BREAK
case 39:
YY_RULE_SETUP
#line 71 "yaoosl.l"
{ return YST_INT16; }
    YY_BREAK
case 40:
YY_RULE_SETUP
#line 72 "yaoosl.l"
{ return YST_UINT16; }
    YY_BREAK
case 41:
YY_RULE_SETUP
#line 73 "yaoosl.l"
{ return YST_INT32; }
    YY_BREAK
case 42:
YY_RULE_SETUP
#line 74 "yaoosl.l"
{ return YST_UINT32; }
    YY_BREAK
case 43:
YY_RULE_SETUP
#line 75 "yaoosl.l"
{ return YST_INT64; }
    YY_BREAK
case 44:
YY_RULE_SETUP
#line 76 "yaoosl.l"
{ return YST_UINT64; }
    YY_BREAK
case 45:
YY_RULE_SETUP
#line 77 "yaoosl.l"
{ return YST_FLOAT; }
    YY_BREAK
case 46:
YY_RULE_SETUP
#line 78 "yaoosl.l"
{ return YST_DOUBLE; }
    YY_BREAK
case 47:
YY_RULE_SETUP
#line 80 "yaoosl.l"
{ return YST_CURLYO; }
    YY_BREAK
case 48:
YY_RULE_SETUP
#line 81 "yaoosl.l"
{ return YST_CURLYC; }
    YY_BREAK
case 49:
YY_RULE_SETUP
#line 82 "yaoosl.l"
{ return YST_ROUNDO; }
    YY_BREAK
case 50:
YY_RULE_SETUP
#line 83 "yaoosl.l"
{ return YST_ROUNDC; }
    YY_BREAK
case 51:
YY_RULE_SETUP
#line 84 "yaoosl.l"
{ return YST_SQUAREO; }
    YY_BREAK
case 52:
YY_RULE_SETUP
#line 85 "yaoosl.l"
{ return YST_SQUAREC; }
    YY_BREAK
case 53:
YY_RULE_SETUP
#line 86 "yaoosl.l"
{ return YST_SEMICOLON; }
    YY_BREAK
case 54:
YY_RULE_SETUP
#line 87 "yaoosl.l"
{ return YST_COMMA; }
    YY_BREAK
case 55:
YY_RULE_SETUP
#line 88 "yaoosl.l"
{ return YST_GET; }
    YY_BREAK
case 56:
YY_RULE_SETUP
#line 89 "yaoosl.l"
{ return YST_SET; }
    YY_BREAK
case 57:
YY_RULE_SETUP
#line 90 "yaoosl.l"
{ return YST_THIS; }
    YY_BREAK
case 58:
YY_RULE_SETUP
#line 91 "yaoosl.l"
{ return YST_PLUSPLUS; }
    YY_BREAK
case 59:
YY_RULE_SETUP
#line 92 "yaoosl.l"
{ return YST_PLUS; }
    YY_BREAK
case 60:
YY_RULE_SETUP
#line 93 "yaoosl.l"
{ return YST_MINUSMINUS; }
    YY_BREAK
case 61:
YY_RULE_SETUP
#line 94 "yaoosl.l"
{ return YST_MINUS; }
    YY_BREAK
case 62:
YY_RULE_SETUP
#line 95 "yaoosl.l"
{ return YST_STAR; }
    YY_BREAK
case 63:
YY_RULE_SETUP
#line 96 "yaoosl.l"
{ return YST_SLASH; }
    YY_BREAK
case 64:
YY_RULE_SETUP
#line 97 "yaoosl.l"
{ return YST_LTLT; }
    YY_BREAK
case 65:
YY_RULE_SETUP
#line 98 "yaoosl.l"
{ return YST_LTEQUAL; }
    YY_BREAK
case 66:
YY_RULE_SETUP
#line 99 "yaoosl.l"
{ return YST_LT; }
    YY_BREAK
case 67:
YY_RULE_SETUP
#line 100 "yaoosl.l"
{ return YST_GTGT; }
    YY_BREAK
case 68:
YY_RULE_SETUP
#line 101 "yaoosl.l"
{ return YST_GTEQUAL; }
    YY_BREAK
case 69:
YY_RULE_SETUP
#line 102 "yaoosl.l"
{ return YST_GT; }
    YY_BREAK
case 70:
YY_RULE_SETUP
#line 103 "yaoosl.l"
{ return YST_EQUALEQUAL; }
    YY_BREAK
case 71:
YY_RULE_SETUP
#line 104 "yaoosl.l"
{ return YST_EXCLAMATIONMARKEQUAL; }
    YY_BREAK
case 72:
YY_RULE_SETUP
#line 105 "yaoosl.l"
{ return YST_ISNOT; }
    YY_BREAK
case 73:
YY_RULE_SETUP
#line 106 "yaoosl.l"
{ return YST_EXCLAMATIONMARK; }
    YY_BREAK
case 74:
YY_RULE_SETUP
#line 107 "yaoosl.l"
{ return YST_TYPEOF; }
    YY_BREAK
case 75:
YY_RULE_SETUP
#line 108 "yaoosl.l"
{ return YST_AUTO; }
    YY_BREAK
case 76:
YY_RULE_SETUP
#line 109 "yaoosl.l"
{ return YST_EQUAL; }
    YY_BREAK
case 77:
YY_RULE_SETUP
#line 110 "yaoosl.l"
{ return YST_TILDEEQUAL; }
    YY_BREAK
case 78:
YY_RULE_SETUP
#line 111 "yaoosl.l"
{ return YST_TILDE; }
    YY_BREAK
case 79:
YY_RULE_SETUP
#line 112 "yaoosl.l"
{ return YST_CIRCUMFLEXEQUAL; }
    YY_BREAK
case 80:
YY_RULE_SETUP
#line 113 "yaoosl.l"
{ return YST_CIRCUMFLEX; }
    YY_BREAK
case 81:
YY_RULE_SETUP
#line 114 "yaoosl.l"
{ return YST_ANDEQUAL; }
    YY_BREAK
case 82:
YY_RULE_SETUP
#line 115 "yaoosl.l"
{ return YST_ANDAND; }
    YY_BREAK
case 83:
YY_RULE_SETUP
#line 116 "yaoosl.l"
{ return YST_AND; }
    YY_BREAK
case 84:
YY_RULE_SETUP
#line 117 "yaoosl.l"
{ return YST_SLASHEQUAL; }
    YY_BREAK
case 85:
YY_RULE_SETUP
#line 118 "yaoosl.l"
{ return YST_STAREQUAL; }
    YY_BREAK
case 86:
YY_RULE_SETUP
#line 119 "yaoosl.l"
{ return YST_MINUSEQUAL; }
    YY_BREAK
case 87:
YY_RULE_SETUP
#line 120 "yaoosl.l"
{ return YST_PLUSEQUAL; }
    YY_BREAK
case 88:
YY_RULE_SETUP
#line 121 "yaoosl.l"
{ return YST_PERCENTEQUAL; }
    YY_BREAK
case 89:
YY_RULE_SETUP
#line 122 "yaoosl.l"
{ return YST_PERCENT; }
    YY_BREAK
case 90:
YY_RULE_SETUP
#line 123 "yaoosl.l"
{ return YST_QUESTIONMARK; }
    YY_BREAK
case 91:
YY_RULE_SETUP
#line 124 "yaoosl.l"
{ return YST_VLINEEQUAL; }
    YY_BREAK
case 92:
YY_RULE_SETUP
#line 125 "yaoosl.l"
{ return YST_VLINEVLINE; }
    YY_BREAK
case 93:
YY_RULE_SETUP
#line 126 "yaoosl.l"
{ return YST_VLINE; }
    YY_BREAK
case 94:
YY_RULE_SETUP
#line 127 "yaoosl.l"
{ return YST_IS; }
    YY_BREAK
case 95:
YY_RULE_SETUP
#line 128 "yaoosl.l"
{ return YST_TRUE; }
    YY_BREAK
case 96:
YY_RULE_SETUP
#line 129 "yaoosl.l"
{ return YST_FALSE; }
    YY_BREAK
case 97:
YY_RULE_SETUP
#line 130 "yaoosl.l"
{ return YST_DOT; }
    YY_BREAK
case 98:
YY_RULE_SETUP
#line 131 "yaoosl.l"
{ yaoosl_lval.str = strdup(yytext); return YST_NUMBER; }
    YY_BREAK
case 99:
YY_RULE_SETUP
#line 132 "yaoosl.l"
{ yaoosl_lval.str = strdup(yytext); return YST_HEXNUMBER; }
    YY_BREAK
case 100:
YY_RULE_SETUP
#line 133 "yaoosl.l"
{ yaoosl_lval.str = strdup(yytext); return YST_BINARYNUMBER; }
    YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 134 "yaoosl.l"
{ yaoosl_lval.str = strdup(yytext); return YST_STRINGVAL; }
    YY_BREAK
case 102:
/* rule 102 can match eol */
YY_RULE_SETUP
#line 135 "yaoosl.l"
{ yaoosl_lval.str = strdup(yytext); return YST_CHARVAL; }
    YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 136 "yaoosl.l"
;
    YY_BREAK
case 104:
YY_RULE_SETUP
#line 138 "yaoosl.l"
{ yaoosl_lval.str = strdup(yytext); return YST_NAME; }
    YY_BREAK
case 105:
YY_RULE_SETUP
#line 140 "yaoosl.l"
ECHO;
    YY_BREAK
#line 1881 "lex.yaoosl_.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CCOMMENT):
    yyterminate();

    case YY_END_OF_BUFFER:
        {
        /* Amount of text matched not including the EOB char. */
        int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

        /* Undo the effects of YY_DO_BEFORE_ACTION. */
        *yy_cp = yyg->yy_hold_char;
        YY_RESTORE_YY_MORE_OFFSET

        if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
            {
            /* We're scanning a new file or input source.  It's
             * possible that this happened because the user
             * just pointed yyin at a new source and called
             * yylex().  If so, then we have to assure
             * consistency between YY_CURRENT_BUFFER and our
             * globals.  Here is the right place to do so, because
             * this is the first action (other than possibly a
             * back-up) that will match for the new input source.
             */
            yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
            YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
            YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
            }

        /* Note that here we test for yy_c_buf_p "<=" to the position
         * of the first EOB in the buffer, since yy_c_buf_p will
         * already have been incremented past the NUL character
         * (since all states make transitions on EOB to the
         * end-of-buffer state).  Contrast this with the test
         * in input().
         */
        if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
            { /* This was really a NUL. */
            yy_state_type yy_next_state;

            yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

            yy_current_state = yy_get_previous_state( yyscanner );

            /* Okay, we're now positioned to make the NUL
             * transition.  We couldn't have
             * yy_get_previous_state() go ahead and do it
             * for us because it doesn't know how to deal
             * with the possibility of jamming (and we don't
             * want to build jamming into it because then it
             * will run more slowly).
             */

            yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

            yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

            if ( yy_next_state )
                {
                /* Consume the NUL. */
                yy_cp = ++yyg->yy_c_buf_p;
                yy_current_state = yy_next_state;
                goto yy_match;
                }

            else
                {
                yy_cp = yyg->yy_last_accepting_cpos;
                yy_current_state = yyg->yy_last_accepting_state;
                goto yy_find_action;
                }
            }

        else switch ( yy_get_next_buffer( yyscanner ) )
            {
            case EOB_ACT_END_OF_FILE:
                {
                yyg->yy_did_buffer_switch_on_eof = 0;

                if ( yywrap( yyscanner ) )
                    {
                    /* Note: because we've taken care in
                     * yy_get_next_buffer() to have set up
                     * yytext, we can now set up
                     * yy_c_buf_p so that if some total
                     * hoser (like flex itself) wants to
                     * call the scanner after we return the
                     * YY_NULL, it'll still work - another
                     * YY_NULL will get returned.
                     */
                    yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

                    yy_act = YY_STATE_EOF(YY_START);
                    goto do_action;
                    }

                else
                    {
                    if ( ! yyg->yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;
                    }
                break;
                }

            case EOB_ACT_CONTINUE_SCAN:
                yyg->yy_c_buf_p =
                    yyg->yytext_ptr + yy_amount_of_matched_text;

                yy_current_state = yy_get_previous_state( yyscanner );

                yy_cp = yyg->yy_c_buf_p;
                yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
                goto yy_match;

            case EOB_ACT_LAST_MATCH:
                yyg->yy_c_buf_p =
                &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

                yy_current_state = yy_get_previous_state( yyscanner );

                yy_cp = yyg->yy_c_buf_p;
                yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
                goto yy_find_action;
            }
        break;
        }

    default:
        YY_FATAL_ERROR(
            "fatal flex scanner internal error--no action found" );
    } /* end of action switch */
        } /* end of scanning one token */
    } /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
    char *source = yyg->yytext_ptr;
    int number_to_move, i;
    int ret_val;

    if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
        YY_FATAL_ERROR(
        "fatal flex scanner internal error--end of buffer missed" );

    if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
        { /* Don't try to fill the buffer, so this is an EOF. */
        if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
            {
            /* We matched a single character, the EOB, so
             * treat this as a final EOF.
             */
            return EOB_ACT_END_OF_FILE;
            }

        else
            {
            /* We matched some text prior to the EOB, first
             * process it.
             */
            return EOB_ACT_LAST_MATCH;
            }
        }

    /* Try to read more data. */

    /* First move last chars to start of buffer. */
    number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

    for ( i = 0; i < number_to_move; ++i )
        *(dest++) = *(source++);

    if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
        /* don't do the read, it's not guaranteed to return an EOF,
         * just force an EOF
         */
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

    else
        {
            int num_to_read =
            YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

        while ( num_to_read <= 0 )
            { /* Not enough room in the buffer - grow it. */

            /* just a shorter name for the current buffer */
            YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

            int yy_c_buf_p_offset =
                (int) (yyg->yy_c_buf_p - b->yy_ch_buf);

            if ( b->yy_is_our_buffer )
                {
                int new_size = b->yy_buf_size * 2;

                if ( new_size <= 0 )
                    b->yy_buf_size += b->yy_buf_size / 8;
                else
                    b->yy_buf_size *= 2;

                b->yy_ch_buf = (char *)
                    /* Include room in for 2 EOB chars. */
                    yyrealloc( (void *) b->yy_ch_buf,
                             (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
                }
            else
                /* Can't grow it, we don't own it. */
                b->yy_ch_buf = NULL;

            if ( ! b->yy_ch_buf )
                YY_FATAL_ERROR(
                "fatal error - scanner input buffer overflow" );

            yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

            num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
                        number_to_move - 1;

            }

        if ( num_to_read > YY_READ_BUF_SIZE )
            num_to_read = YY_READ_BUF_SIZE;

        /* Read in more data. */
        YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
            yyg->yy_n_chars, num_to_read );

        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
        }

    if ( yyg->yy_n_chars == 0 )
        {
        if ( number_to_move == YY_MORE_ADJ )
            {
            ret_val = EOB_ACT_END_OF_FILE;
            yyrestart( yyin  , yyscanner);
            }

        else
            {
            ret_val = EOB_ACT_LAST_MATCH;
            YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
                YY_BUFFER_EOF_PENDING;
            }
        }

    else
        ret_val = EOB_ACT_CONTINUE_SCAN;

    if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
        /* Extend the array by 50%, plus the number we really need. */
        int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
        YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
            (void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
        if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
            YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
        /* "- 2" to take care of EOB's */
        YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
    }

    yyg->yy_n_chars += number_to_move;
    YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
    YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

    yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

    return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
    yy_state_type yy_current_state;
    char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_current_state = yyg->yy_start;

    for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
        {
        YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
        if ( yy_accept[yy_current_state] )
            {
            yyg->yy_last_accepting_state = yy_current_state;
            yyg->yy_last_accepting_cpos = yy_cp;
            }
        while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
            {
            yy_current_state = (int) yy_def[yy_current_state];
            if ( yy_current_state >= 518 )
                yy_c = yy_meta[yy_c];
            }
        yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
        }

    return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
    int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
    char *yy_cp = yyg->yy_c_buf_p;

    YY_CHAR yy_c = 1;
    if ( yy_accept[yy_current_state] )
        {
        yyg->yy_last_accepting_state = yy_current_state;
        yyg->yy_last_accepting_cpos = yy_cp;
        }
    while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
        {
        yy_current_state = (int) yy_def[yy_current_state];
        if ( yy_current_state >= 518 )
            yy_c = yy_meta[yy_c];
        }
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam = (yy_current_state == 517);

    (void)yyg;
    return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
    int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    *yyg->yy_c_buf_p = yyg->yy_hold_char;

    if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
        {
        /* yy_c_buf_p now points to the character we want to return.
         * If this occurs *before* the EOB characters, then it's a
         * valid NUL; if not, then we've hit the end of the buffer.
         */
        if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
            /* This was really a NUL. */
            *yyg->yy_c_buf_p = '\0';

        else
            { /* need more input */
            int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
            ++yyg->yy_c_buf_p;

            switch ( yy_get_next_buffer( yyscanner ) )
                {
                case EOB_ACT_LAST_MATCH:
                    /* This happens because yy_g_n_b()
                     * sees that we've accumulated a
                     * token and flags that we need to
                     * try matching the token before
                     * proceeding.  But for input(),
                     * there's no matching to consider.
                     * So convert the EOB_ACT_LAST_MATCH
                     * to EOB_ACT_END_OF_FILE.
                     */

                    /* Reset buffer status. */
                    yyrestart( yyin , yyscanner);

                    /*FALLTHROUGH*/

                case EOB_ACT_END_OF_FILE:
                    {
                    if ( yywrap( yyscanner ) )
                        return 0;

                    if ( ! yyg->yy_did_buffer_switch_on_eof )
                        YY_NEW_FILE;
#ifdef __cplusplus
                    return yyinput(yyscanner);
#else
                    return input(yyscanner);
#endif
                    }

                case EOB_ACT_CONTINUE_SCAN:
                    yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
                    break;
                }
            }
        }

    c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
    *yyg->yy_c_buf_p = '\0';	/* preserve yytext */
    yyg->yy_hold_char = *++yyg->yy_c_buf_p;

    return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
        YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
    }

    yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
    yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* TODO. We should be able to replace this entire function body
     * with
     *		yypop_buffer_state();
     *		yypush_buffer_state(new_buffer);
     */
    yyensure_buffer_stack (yyscanner);
    if ( YY_CURRENT_BUFFER == new_buffer )
        return;

    if ( YY_CURRENT_BUFFER )
        {
        /* Flush out information for old buffer. */
        *yyg->yy_c_buf_p = yyg->yy_hold_char;
        YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
        }

    YY_CURRENT_BUFFER_LVALUE = new_buffer;
    yy_load_buffer_state( yyscanner );

    /* We don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
    yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
    yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
    yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
    YY_BUFFER_STATE b;
    
    b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
    if ( ! b )
        YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
    if ( ! b->yy_ch_buf )
        YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

    b->yy_is_our_buffer = 1;

    yy_init_buffer( b, file , yyscanner);

    return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    if ( ! b )
        return;

    if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
        YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

    if ( b->yy_is_our_buffer )
        yyfree( (void *) b->yy_ch_buf , yyscanner );

    yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
    int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_flush_buffer( b , yyscanner);

    b->yy_input_file = file;
    b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
    errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    if ( ! b )
        return;

    b->yy_n_chars = 0;

    /* We always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[0];

    b->yy_at_bol = 1;
    b->yy_buffer_status = YY_BUFFER_NEW;

    if ( b == YY_CURRENT_BUFFER )
        yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    if (new_buffer == NULL)
        return;

    yyensure_buffer_stack(yyscanner);

    /* This block is copied from yy_switch_to_buffer. */
    if ( YY_CURRENT_BUFFER )
        {
        /* Flush out information for old buffer. */
        *yyg->yy_c_buf_p = yyg->yy_hold_char;
        YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
        }

    /* Only push if top exists. Otherwise, replace top. */
    if (YY_CURRENT_BUFFER)
        yyg->yy_buffer_stack_top++;
    YY_CURRENT_BUFFER_LVALUE = new_buffer;

    /* copied from yy_switch_to_buffer. */
    yy_load_buffer_state( yyscanner );
    yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    if (!YY_CURRENT_BUFFER)
        return;

    yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
    YY_CURRENT_BUFFER_LVALUE = NULL;
    if (yyg->yy_buffer_stack_top > 0)
        --yyg->yy_buffer_stack_top;

    if (YY_CURRENT_BUFFER) {
        yy_load_buffer_state( yyscanner );
        yyg->yy_did_buffer_switch_on_eof = 1;
    }
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
    yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    if (!yyg->yy_buffer_stack) {

        /* First allocation is just for 2 elements, since we don't know if this
         * scanner will even need a stack. We use 2 instead of 1 to avoid an
         * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
        yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
                                (num_to_alloc * sizeof(struct yy_buffer_state*)
                                , yyscanner);
        if ( ! yyg->yy_buffer_stack )
            YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

        memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

        yyg->yy_buffer_stack_max = num_to_alloc;
        yyg->yy_buffer_stack_top = 0;
        return;
    }

    if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

        /* Increase the buffer to prepare for a possible push. */
        yy_size_t grow_size = 8 /* arbitrary grow size */;

        num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
        yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
                                (yyg->yy_buffer_stack,
                                num_to_alloc * sizeof(struct yy_buffer_state*)
                                , yyscanner);
        if ( ! yyg->yy_buffer_stack )
            YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

        /* zero only the new slots.*/
        memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
        yyg->yy_buffer_stack_max = num_to_alloc;
    }
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
    YY_BUFFER_STATE b;
    
    if ( size < 2 ||
         base[size-2] != YY_END_OF_BUFFER_CHAR ||
         base[size-1] != YY_END_OF_BUFFER_CHAR )
        /* They forgot to leave room for the EOB's. */
        return NULL;

    b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
    if ( ! b )
        YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

    b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
    b->yy_buf_pos = b->yy_ch_buf = base;
    b->yy_is_our_buffer = 0;
    b->yy_input_file = NULL;
    b->yy_n_chars = b->yy_buf_size;
    b->yy_is_interactive = 0;
    b->yy_at_bol = 1;
    b->yy_fill_buffer = 0;
    b->yy_buffer_status = YY_BUFFER_NEW;

    yy_switch_to_buffer( b , yyscanner );

    return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
    return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
    YY_BUFFER_STATE b;
    char *buf;
    yy_size_t n;
    int i;
    
    /* Get memory for full buffer, including space for trailing EOB's. */
    n = (yy_size_t) (_yybytes_len + 2);
    buf = (char *) yyalloc( n , yyscanner );
    if ( ! buf )
        YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

    for ( i = 0; i < _yybytes_len; ++i )
        buf[i] = yybytes[i];

    buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

    b = yy_scan_buffer( buf, n , yyscanner);
    if ( ! b )
        YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

    /* It's okay to grow etc. this buffer, and we should throw it
     * away when we're done.
     */
    b->yy_is_our_buffer = 1;

    return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    (void)yyg;
    fprintf( stderr, "%s\n", msg );
    exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
    do \
        { \
        /* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
        yytext[yyleng] = yyg->yy_hold_char; \
        yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
        yyg->yy_hold_char = *yyg->yy_c_buf_p; \
        *yyg->yy_c_buf_p = '\0'; \
        yyleng = yyless_macro_arg; \
        } \
    while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
    while(YY_CURRENT_BUFFER){
        yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
        YY_CURRENT_BUFFER_LVALUE = NULL;
        yypop_buffer_state(yyscanner);
    }

    /* Destroy the stack itself. */
    yyfree(yyg->yy_buffer_stack , yyscanner);
    yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    (void)yyg;

    int i;
    for ( i = 0; i < n; ++i )
        s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
    int n;
    for ( n = 0; s[n]; ++n )
        ;

    return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    (void)yyg;
    return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    (void)yyg;

    /* The cast to (char *) in the following accommodates both
     * implementations that use char* generic pointers, and those
     * that use void* generic pointers.  It works with the latter
     * because both ANSI C and C++ allow castless assignment from
     * any pointer type to void*, and deal with argument conversions
     * as though doing an assignment.
     */
    return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    (void)yyg;
    free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 140 "yaoosl.l"


/* Start code copied to scanner output */

void yaoosl_yyscan_string(const char* str, yyscan_t yyscanner)
{
    yy_scan_string(str, yyscanner);
}

/* End code copied to scanner output */
